# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/UIMainWindowForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(619, 506)
        MainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 601, 191))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 601, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.lineNumber = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineNumber.setObjectName("lineNumber")
        self.gridLayout.addWidget(self.lineNumber, 0, 2, 1, 1)
        self.northing = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.northing.setObjectName("northing")
        self.gridLayout.addWidget(self.northing, 5, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 1)
        self.pointDistance = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pointDistance.setObjectName("pointDistance")
        self.gridLayout.addWidget(self.pointDistance, 4, 4, 1, 1)
        self.lineDistance = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineDistance.setObjectName("lineDistance")
        self.gridLayout.addWidget(self.lineDistance, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 1, 1, 1)
        self.lineAzimuth = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineAzimuth.setObjectName("lineAzimuth")
        self.gridLayout.addWidget(self.lineAzimuth, 6, 2, 1, 1)
        self.lineInterval = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineInterval.setObjectName("lineInterval")
        self.gridLayout.addWidget(self.lineInterval, 2, 2, 1, 1)
        self.easting = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.easting.setObjectName("easting")
        self.gridLayout.addWidget(self.easting, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.pointInterval = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pointInterval.setObjectName("pointInterval")
        self.gridLayout.addWidget(self.pointInterval, 2, 4, 1, 1)
        self.pointNumber = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pointNumber.setObjectName("pointNumber")
        self.gridLayout.addWidget(self.pointNumber, 0, 4, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 280, 601, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 601, 97))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.numberOfLines = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.numberOfLines.setObjectName("numberOfLines")
        self.gridLayout_2.addWidget(self.numberOfLines, 0, 2, 1, 1)
        self.generateCsv = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateCsv.sizePolicy().hasHeightForWidth())
        self.generateCsv.setSizePolicy(sizePolicy)
        self.generateCsv.setObjectName("generateCsv")
        self.gridLayout_2.addWidget(self.generateCsv, 1, 1, 1, 1)
        self.generateSps21 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateSps21.sizePolicy().hasHeightForWidth())
        self.generateSps21.setSizePolicy(sizePolicy)
        self.generateSps21.setObjectName("generateSps21")
        self.gridLayout_2.addWidget(self.generateSps21, 2, 1, 1, 1)
        self.numberOfPoints = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.numberOfPoints.setObjectName("numberOfPoints")
        self.gridLayout_2.addWidget(self.numberOfPoints, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 210, 601, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pointType = QtWidgets.QComboBox(self.groupBox_3)
        self.pointType.setGeometry(QtCore.QRect(10, 30, 86, 25))
        self.pointType.setObjectName("pointType")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 619, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Origin = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/grid_generator/icons/folder-open-document-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Origin.setIcon(icon)
        self.actionOpen_Origin.setObjectName("actionOpen_Origin")
        self.actionSave_Origin = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/grid_generator/icons/disk-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Origin.setIcon(icon1)
        self.actionSave_Origin.setObjectName("actionSave_Origin")
        self.actionSave_As_Origin = QtWidgets.QAction(MainWindow)
        self.actionSave_As_Origin.setIcon(icon1)
        self.actionSave_As_Origin.setObjectName("actionSave_As_Origin")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/grid_generator/icons/cross-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/grid_generator/icons/key-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLicense.setIcon(icon3)
        self.actionLicense.setObjectName("actionLicense")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/grid_generator/icons/information-button-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen_Origin)
        self.menuFile.addAction(self.actionSave_Origin)
        self.menuFile.addAction(self.actionSave_As_Origin)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionLicense)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineNumber, self.pointNumber)
        MainWindow.setTabOrder(self.pointNumber, self.lineInterval)
        MainWindow.setTabOrder(self.lineInterval, self.pointInterval)
        MainWindow.setTabOrder(self.pointInterval, self.lineDistance)
        MainWindow.setTabOrder(self.lineDistance, self.pointDistance)
        MainWindow.setTabOrder(self.pointDistance, self.easting)
        MainWindow.setTabOrder(self.easting, self.northing)
        MainWindow.setTabOrder(self.northing, self.lineAzimuth)
        MainWindow.setTabOrder(self.lineAzimuth, self.numberOfLines)
        MainWindow.setTabOrder(self.numberOfLines, self.numberOfPoints)
        MainWindow.setTabOrder(self.numberOfPoints, self.generateCsv)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("MainWindow", "Origin"))
        self.label_5.setText(_translate("MainWindow", "Line Distance"))
        self.label_4.setText(_translate("MainWindow", "Point Interval"))
        self.label.setText(_translate("MainWindow", "Easting"))
        self.label_6.setText(_translate("MainWindow", "Point Distance"))
        self.label_7.setText(_translate("MainWindow", "Line Number"))
        self.label_2.setText(_translate("MainWindow", "Northing"))
        self.label_3.setText(_translate("MainWindow", "Line Azimuth"))
        self.label_8.setText(_translate("MainWindow", "Point Number"))
        self.label_9.setText(_translate("MainWindow", "Line Interval"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Generate"))
        self.generateCsv.setText(_translate("MainWindow", "To CSV"))
        self.generateSps21.setText(_translate("MainWindow", "To SPS 2.1"))
        self.label_11.setText(_translate("MainWindow", "Number of Points"))
        self.label_14.setText(_translate("MainWindow", "Number of Lines"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Point Type"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_Origin.setText(_translate("MainWindow", "Open Origin"))
        self.actionSave_Origin.setText(_translate("MainWindow", "Save Origin"))
        self.actionSave_As_Origin.setText(_translate("MainWindow", "Save As Origin"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionLicense.setText(_translate("MainWindow", "License"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
import resources_rc
